GET {{BASE_URL}}/users 
Content-Type: "application/json"

{}

###

GET {{BASE_URL}}/users?username=nam
Content-Type: application/json

{}

###

GET {{BASE_URL}}/users?id=1
Content-Type: application/json

{}

###

POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "username": "nam",
    "password": "LI90EDlR4oFE"
}

###

PUT {{BASE_URL}}/users
Content-Type: application/json

{
  "id": "1",
  "username": "nam",
  "password": "Pass1234",
  "fullName": "Le Nguyen Nhat Nam",
  "email": "namlenguyen@gmail.com",
  "phoneNumber": "099912345",
  "dateOfBirth": "01/01/1999",
  "gender": "Male"
}

###

POST {{BASE_URL}}/users
Content-Type: application/json

{
  "id": "0",
  "username": "longnguyen",
  "password": "Pass1234",
  "fullName": "Le Nguyen Nhat Nam",
  "email": "namlenguyen@gmail.com",
  "phoneNumber": "099912345",
  "dateOfBirth": "01/01/1999",
  "gender": "Male"
}

###

PUT {{BASE_URL}}/users/reset-password
Content-Type: application/json

{
  "userId": 1
}